# Generated by Django 2.2.5 on 2021-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='settings.MEDIA_ROOT/images/default.png', upload_to='', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.FileField(default='settings.MEDIA_ROOT/videos/default.mp4', upload_to='', verbose_name='视频'),
        ),
    ]
