# Generated by Django 2.2.5 on 2021-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20210611_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='settings.MEDIA_ROOT/images/default.png', upload_to='D:\\media\\images', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.FileField(default='settings.MEDIA_ROOT/videos/default.mp4', upload_to='D:\\media\\videos', verbose_name='视频'),
        ),
    ]
