# Generated by Django 2.2.5 on 2021-06-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20210611_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='TestModel.User'),
        ),
    ]
